name: KIM Release

on:
  push:
    tags:
      - '*'  # Trigger on tag pushes

jobs:
  run-release-tests:
    permissions:
      actions: read
      contents: read
    uses: ./.github/workflows/run-tests.yaml

  generate-release:
    needs: run-release-tests
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed for creating releases and uploading assets
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'

      - name: Install crd-ref-docs tool
        run: go install github.com/elastic/crd-ref-docs@latest

      - name: Generate CRD documentation
        run: |
          $HOME/go/bin/crd-ref-docs \
            --renderer=markdown \
            --source-path=./api \
            --config=./config/crd/crd-doc-config.yaml \
            --output-path=./config/crd/crd-docs.md

      - name: Create Release and Generate Notes
        uses: softprops/action-gh-release@v2
        with:
          files: ./config/crd/crd-docs.md
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  upload-release-report:
    needs: generate-release
    if: success()
    permissions:
    permissions:
      actions: read
      contents: read
    uses: kyma-project/compliancy/.github/workflows/upload-release-report.yml@main
    with:
      release_version: ${{ github.ref_name }}
    secrets:
      RELEASE_LOG_UPLOADER_SA: ${{ secrets.RELEASE_LOG_UPLOADER_SA }}

